FROM docker.beryju.org/p2/dev:latest as static-build

COPY ./p2/ /app/p2
COPY ./manage.py /app/
COPY ./requirements.txt /app/

WORKDIR /app/

ENV P2_POSTGRESQL__USER=p2
# CI Password, same as in .gitlab-ci.yml
ENV P2_POSTGRESQL__PASSWORD="EK-5jnKfjrGRm<77"
RUN ./manage.py collectstatic --no-input

FROM nginx:latest

COPY --from=static-build /app/static /static/_/static/
COPY ./p2/ui/nginx.conf /etc/nginx/nginx.conf
