FROM python:3.7

COPY ./p2/ /app/p2
COPY ./requirements.txt /app/
COPY ./requirements-dev.txt /app/

WORKDIR /app/

RUN apt-get update && apt-get install build-essential libffi-dev libsasl2-dev python-dev libldap2-dev libssl-dev libpq-dev -y && \
     pip install -U -r requirements-dev.txt && \
     rm -rf /app/* && \
     rm -rf /var/cache/apt/archives/*
