FROM python:3.7-alpine

COPY ./Pipfile /app/
COPY ./Pipfile.lock /app/

WORKDIR /app/

RUN apk update && \
    apk add --no-cache openssl-dev libmagic build-base jpeg libffi-dev gcc musl-dev libgcc openssl-dev jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev postgresql-dev && \
    pip install pipenv --no-cache-dir && \
    pipenv lock -r > requirements.txt && \
    pip install -r requirements.txt  --no-cache-dir && \
    adduser -S p2 && \
    chown -R p2 /app
