# Generated by Django 2.1.7 on 2019-03-24 16:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStorage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('values', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField()),
            ],
            options={
                'permissions': (('List contents', 'list'),),
            },
        ),
        migrations.CreateModel(
            name='LocalFileStorage',
            fields=[
                ('basestorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='p2_core.BaseStorage')),
            ],
            options={
                'abstract': False,
            },
            bases=('p2_core.basestorage',),
        ),
        migrations.AddField(
            model_name='volume',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_core.BaseStorage'),
        ),
        migrations.AddField(
            model_name='blob',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_core.Volume'),
        ),
        migrations.AlterUniqueTogether(
            name='blob',
            unique_together={('path', 'volume')},
        ),
    ]
