# Generated by Django 2.1.7 on 2019-03-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0003_auto_20190324_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'permissions': (('list_contents', 'List contents'), ('use_volume', 'Use Volume'))},
        ),
    ]
