# Generated by Django 2.1.7 on 2019-03-25 15:00

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0006_auto_20190325_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
