# Generated by Django 2.1.7 on 2019-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0007_auto_20190325_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basestorage',
            options={'permissions': (('use_storage', 'Can use storage'),)},
        ),
    ]
