# Generated by Django 2.2 on 2019-04-23 18:31

from django.db import migrations, models


def update_prefix(apps, schema_editor):
    Blob = apps.get_model("p2_core", "Blob")
    for blob in Blob.objects.all():
        # blob.__update_prefix()
        blob.save()


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0009_auto_20190423_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='prefix',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(update_prefix),
        migrations.AlterField(
            model_name='blob',
            name='prefix',
            field=models.TextField(),
        ),
    ]
