# Generated by Django 2.2 on 2019-04-24 11:54

from django.db import migrations


def create_default_user(apps, schema_editor):
    from django.contrib.auth.models import User
    from guardian.conf import settings as guardian_settings
    # Ignore Anonymous User
    if not User.objects.all().exclude(username=guardian_settings.ANONYMOUS_USER_NAME).exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@p2.local',
            password='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0010_blob_prefix'),
    ]

    operations = [
        migrations.RunPython(create_default_user)
    ]
