# Generated by Django 2.2 on 2019-04-30 09:24

import uuid

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0011_create_default_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfilestorage',
            name='basestorage_ptr',
        ),
        migrations.DeleteModel(
            name='LocalFileStorage',
        ),
        migrations.RenameModel(
            old_name='BaseStorage',
            new_name='Storage',
        ),
        migrations.AddField(
            model_name='Storage',
            name='controller',
            field=models.TextField(choices=[('p2.core.storage.null.NullStorageController', 'NullStorageController'), ('p2.storage.local.controller.LocalStorageController', 'LocalStorageController')])
        ),
        migrations.AlterField(
            model_name='volume',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_core.Storage'),
        ),
    ]
