# Generated by Django 2.2 on 2019-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0013_auto_20190430_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
