# Generated by Django 2.2 on 2019-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0014_component_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='controller_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='controller_path',
            field=models.TextField(),
        ),
    ]
