# Generated by Django 2.2 on 2019-04-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0015_auto_20190430_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='controller_path',
            field=models.TextField(choices=[('p2.components.image.controller.ImageController', 'ImageController'), ('p2.components.quota.controller.QuotaController', 'QuotaController')]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='controller_path',
            field=models.TextField(choices=[('p2.core.storages.null.NullStorageController', 'NullStorageController'), ('p2.storage.local.controller.LocalStorageController', 'LocalStorageController')]),
        ),
    ]
