# Generated by Django 2.2 on 2019-05-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0016_auto_20190430_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='controller_path',
            field=models.TextField(choices=[('p2.components.image.controller.ImageController', 'ImageController'), ('p2.components.quota.controller.QuotaController', 'QuotaController'), ('p2.components.public_access.controller.PublicAccessController', 'PublicAccessController')]),
        ),
    ]
