# Generated by Django 2.2.1 on 2019-05-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0018_auto_20190515_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'permissions': (('list_volume_contents', 'Can List contents'), ('use_volume', 'Can Use Volume')), 'verbose_name': 'Volume', 'verbose_name_plural': 'Volumes'},
        ),
    ]
