# Generated by Django 2.2.1 on 2019-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0020_create_default_storage_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
