# Generated by Django 2.2 on 2019-04-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_quota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='volume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='p2_core.Volume'),
        ),
    ]
