# Generated by Django 2.2.1 on 2019-05-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='volume',
        ),
    ]
