#!/bin/sh
# config maintainer script for p2
set -e

# source debconf stuff
. /usr/share/debconf/confmodule

dbc_first_version=1.0.0
dbc_dbuser=p2
dbc_dbname=p2

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/config.mysql
    dbc_go p2 "$@"
fi

#DEBHELPER#

exit 0
