#!/bin/bash

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

# you can set the default database encoding to something else
dbc_mysql_createdb_encoding="UTF8"
dbc_generate_include=template:/etc/p2/config.d/database.yml
dbc_generate_include_args="-o template_infile=/usr/share/p2/database.yml"
dbc_go p2 "$@"

if [ -z "`getent group p2`" ]; then
	addgroup --quiet --system p2
fi
if [ -z "`getent passwd p2`" ]; then
	echo " * Creating user and group p2..."
	adduser --quiet --system --home /usr/share/p2 --shell /bin/false --ingroup p2 --disabled-password --disabled-login --gecos "p2 User" p2  >> /var/log/p2/p2.log 2>&1
fi
echo " * Updating binary packages (pillow, pyldap)"
python3 -m pip install --target=/usr/share/p2/vendor/ --no-cache-dir --upgrade --force-reinstall pillow pyldap >> /var/log/p2/p2.log 2>&1
if [ ! -f '/etc/p2/secret_key' ]; then
	echo " * Generating Secret Key"
	python3 -c 'import random; result = "".join([random.choice("abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)") for i in range(50)]); print(result)' > /etc/p2/secret_key 2> /dev/null
fi
chown -R p2: /usr/share/p2/
chown -R p2: /etc/p2/
chown -R p2: /var/log/p2/
chmod 440 /etc/p2/secret_key
echo " * Running Database Migration"
/usr/share/p2/p2.sh migrate
echo " * A superuser can be created with this command '/usr/share/p2/p2.sh createsuperuser'"
echo " * You should probably also adjust your settings in '/etc/p2/config.yml'"

#DEBHELPER#
