# Generated by Django 2.2.1 on 2019-05-14 16:10

import uuid

import django.db.models.deletion
from django.db import migrations, models

import p2.s3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p2_core', '0017_auto_20190503_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipartUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('blob_key', models.TextField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_core.Volume')),
            ],
            options={
                'unique_together': {('volume', 'blob_key')},
            },
        ),
        migrations.CreateModel(
            name='MultipartUploadPart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('part', models.IntegerField()),
                ('temporary_file_path', models.TextField(default=p2.s3.models.make_temp_path)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_s3.MultipartUpload')),
            ],
            options={
                'unique_together': {('upload', 'part')},
            },
        ),
    ]
