# Generated by Django 2.2 on 2019-04-15 21:02

from django.db import migrations, models

import p2.s3.models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3accesskey',
            name='access_key',
            field=models.CharField(default=p2.s3.models.get_access_key, max_length=253),
        ),
        migrations.AlterField(
            model_name='s3accesskey',
            name='secret_key',
            field=models.CharField(default=p2.s3.models.get_access_key, max_length=253),
        ),
        migrations.AlterUniqueTogether(
            name='s3accesskey',
            unique_together={('access_key', 'secret_key')},
        ),
    ]
