# Generated by Django 2.2 on 2019-04-15 21:50

from django.db import migrations, models

import p2.s3.models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_s3', '0002_auto_20190415_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3accesskey',
            name='access_key',
            field=models.CharField(default=p2.s3.models.get_access_key, max_length=20),
        ),
        migrations.AlterField(
            model_name='s3accesskey',
            name='secret_key',
            field=models.CharField(default=p2.s3.models.get_secret_key, max_length=40),
        ),
    ]
