# Generated by Django 2.2 on 2019-04-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_s3', '0003_auto_20190415_2150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='s3accesskey',
            unique_together=set(),
        ),
    ]
