# Generated by Django 2.2 on 2019-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('match', models.TextField()),
                ('blob_query', models.TextField()),
                ('default', models.BooleanField(default=False, unique=True)),
            ],
        ),
    ]
