# Generated by Django 2.2.1 on 2019-06-04 14:02

import uuid

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_serve', '0002_remove_serverule_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serverule',
            name='match',
        ),
        migrations.AddField(
            model_name='serverule',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serverule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
