# Generated by Django 2.2 on 2019-04-15 21:02

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2_log', '0002_auto_20190408_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
