# Generated by Django 2.2 on 2019-04-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_log', '0004_auto_20190430_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logadaptor',
            name='controller_path',
            field=models.TextField(choices=[('p2.log.controllers.database.DatabaseLogController', 'DatabaseLogController')]),
        ),
    ]
