# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/serve.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/serve.proto',
  package='p2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12protos/serve.proto\x12\x02p2\"\x8c\x01\n\x0cServeRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12.\n\x07headers\x18\x03 \x03(\x0b\x32\x1d.p2.ServeRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9b\x01\n\nServeReply\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x10\n\x08matching\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12,\n\x07headers\x18\x04 \x03(\x0b\x32\x1b.p2.ServeReply.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32;\n\x05Serve\x12\x32\n\x0cRetrieveFile\x12\x10.p2.ServeRequest\x1a\x0e.p2.ServeReply\"\x00\x62\x06proto3')
)




_SERVEREQUEST_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='p2.ServeRequest.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='p2.ServeRequest.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='p2.ServeRequest.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=167,
)

_SERVEREQUEST = _descriptor.Descriptor(
  name='ServeRequest',
  full_name='p2.ServeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='p2.ServeRequest.session', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='p2.ServeRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='p2.ServeRequest.headers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERVEREQUEST_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=167,
)


_SERVEREPLY_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='p2.ServeReply.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='p2.ServeReply.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='p2.ServeReply.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=167,
)

_SERVEREPLY = _descriptor.Descriptor(
  name='ServeReply',
  full_name='p2.ServeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='p2.ServeReply.session', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matching', full_name='p2.ServeReply.matching', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='p2.ServeReply.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='p2.ServeReply.headers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERVEREPLY_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=325,
)

_SERVEREQUEST_HEADERSENTRY.containing_type = _SERVEREQUEST
_SERVEREQUEST.fields_by_name['headers'].message_type = _SERVEREQUEST_HEADERSENTRY
_SERVEREPLY_HEADERSENTRY.containing_type = _SERVEREPLY
_SERVEREPLY.fields_by_name['headers'].message_type = _SERVEREPLY_HEADERSENTRY
DESCRIPTOR.message_types_by_name['ServeRequest'] = _SERVEREQUEST
DESCRIPTOR.message_types_by_name['ServeReply'] = _SERVEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServeRequest = _reflection.GeneratedProtocolMessageType('ServeRequest', (_message.Message,), dict(

  HeadersEntry = _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
    DESCRIPTOR = _SERVEREQUEST_HEADERSENTRY,
    __module__ = 'protos.serve_pb2'
    # @@protoc_insertion_point(class_scope:p2.ServeRequest.HeadersEntry)
    ))
  ,
  DESCRIPTOR = _SERVEREQUEST,
  __module__ = 'protos.serve_pb2'
  # @@protoc_insertion_point(class_scope:p2.ServeRequest)
  ))
_sym_db.RegisterMessage(ServeRequest)
_sym_db.RegisterMessage(ServeRequest.HeadersEntry)

ServeReply = _reflection.GeneratedProtocolMessageType('ServeReply', (_message.Message,), dict(

  HeadersEntry = _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
    DESCRIPTOR = _SERVEREPLY_HEADERSENTRY,
    __module__ = 'protos.serve_pb2'
    # @@protoc_insertion_point(class_scope:p2.ServeReply.HeadersEntry)
    ))
  ,
  DESCRIPTOR = _SERVEREPLY,
  __module__ = 'protos.serve_pb2'
  # @@protoc_insertion_point(class_scope:p2.ServeReply)
  ))
_sym_db.RegisterMessage(ServeReply)
_sym_db.RegisterMessage(ServeReply.HeadersEntry)


_SERVEREQUEST_HEADERSENTRY._options = None
_SERVEREPLY_HEADERSENTRY._options = None

_SERVE = _descriptor.ServiceDescriptor(
  name='Serve',
  full_name='p2.Serve',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=327,
  serialized_end=386,
  methods=[
  _descriptor.MethodDescriptor(
    name='RetrieveFile',
    full_name='p2.Serve.RetrieveFile',
    index=0,
    containing_service=None,
    input_type=_SERVEREQUEST,
    output_type=_SERVEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVE)

DESCRIPTOR.services_by_name['Serve'] = _SERVE

# @@protoc_insertion_point(module_scope)
