# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import serve_pb2 as protos_dot_serve__pb2


class ServeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RetrieveFile = channel.unary_unary(
        '/p2.Serve/RetrieveFile',
        request_serializer=protos_dot_serve__pb2.ServeRequest.SerializeToString,
        response_deserializer=protos_dot_serve__pb2.ServeReply.FromString,
        )


class ServeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RetrieveFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RetrieveFile': grpc.unary_unary_rpc_method_handler(
          servicer.RetrieveFile,
          request_deserializer=protos_dot_serve__pb2.ServeRequest.FromString,
          response_serializer=protos_dot_serve__pb2.ServeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'p2.Serve', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
